# Generated by Django 4.2.10 on 2024-02-17 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treningapp', '0002_member_excercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Liczba_Serii',
        ),
    ]
