# Generated by Django 4.2.10 on 2024-02-18 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('calories_per_one', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField()),
                ('executed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('duration', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.PositiveIntegerField(default=1)),
                ('series', models.PositiveIntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainapp.exercise')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainapp.training')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='exercises',
            field=models.ManyToManyField(through='trainapp.TrainingExercise', to='trainapp.exercise'),
        ),
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
