# Generated by Django 4.2.10 on 2024-02-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainapp', '0002_bodypart_exercise_body_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='all_calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50),
        ),
    ]
